const nflPlayers = [
  // ── Arizona Cardinals ─────────────────────────────────────────────────────
  { name: 'Kyler Murray',           team: 'Arizona Cardinals',      position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Marvin Harrison Jr.',    team: 'Arizona Cardinals',      position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Trey McBride',           team: 'Arizona Cardinals',      position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'James Conner',           team: 'Arizona Cardinals',      position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Budda Baker',            team: 'Arizona Cardinals',      position: 'S',  sport: 'Football', cardType: 'Downtown' },
  { name: 'Zaven Collins',          team: 'Arizona Cardinals',      position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Michael Wilson',         team: 'Arizona Cardinals',      position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Sean Murphy-Bunting',    team: 'Arizona Cardinals',      position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Emari Demercado',        team: 'Arizona Cardinals',      position: 'RB', sport: 'Football', cardType: 'Base' },
  { name: 'Bilal Nichols',          team: 'Arizona Cardinals',      position: 'DT', sport: 'Football', cardType: 'Base' },

  // ── Atlanta Falcons ───────────────────────────────────────────────────────
  { name: 'Kirk Cousins',           team: 'Atlanta Falcons',        position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Bijan Robinson',         team: 'Atlanta Falcons',        position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Drake London',           team: 'Atlanta Falcons',        position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Kyle Pitts',             team: 'Atlanta Falcons',        position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Grady Jarrett',          team: 'Atlanta Falcons',        position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'A.J. Terrell',           team: 'Atlanta Falcons',        position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jessie Bates III',       team: 'Atlanta Falcons',        position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Matthew Judon',          team: 'Atlanta Falcons',        position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Ray-Ray McCloud',        team: 'Atlanta Falcons',        position: 'WR', sport: 'Football', cardType: 'Base' },
  { name: 'Younghoe Koo',           team: 'Atlanta Falcons',        position: 'K',  sport: 'Football', cardType: 'Base' },

  // ── Baltimore Ravens ──────────────────────────────────────────────────────
  { name: 'Lamar Jackson',          team: 'Baltimore Ravens',       position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Derrick Henry',          team: 'Baltimore Ravens',       position: 'RB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Mark Andrews',           team: 'Baltimore Ravens',       position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Zay Flowers',            team: 'Baltimore Ravens',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Roquan Smith',           team: 'Baltimore Ravens',       position: 'LB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Kyle Hamilton',          team: 'Baltimore Ravens',       position: 'S',  sport: 'Football', cardType: 'Downtown' },
  { name: 'Marlon Humphrey',        team: 'Baltimore Ravens',       position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Justin Madubuike',       team: 'Baltimore Ravens',       position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Gus Edwards',            team: 'Baltimore Ravens',       position: 'RB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Nelson Agholor',         team: 'Baltimore Ravens',       position: 'WR', sport: 'Football', cardType: 'Parallel' },

  // ── Buffalo Bills ─────────────────────────────────────────────────────────
  { name: 'Josh Allen',             team: 'Buffalo Bills',          position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'James Cook',             team: 'Buffalo Bills',          position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Dalton Kincaid',         team: 'Buffalo Bills',          position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Keon Coleman',           team: 'Buffalo Bills',          position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Dawson Knox',            team: 'Buffalo Bills',          position: 'TE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Ed Oliver',              team: 'Buffalo Bills',          position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Von Miller',             team: 'Buffalo Bills',          position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Tre White',              team: 'Buffalo Bills',          position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Dion Dawkins',           team: 'Buffalo Bills',          position: 'OT', sport: 'Football', cardType: 'Parallel' },
  { name: 'Jordan Poyer',           team: 'Buffalo Bills',          position: 'S',  sport: 'Football', cardType: 'Base' },

  // ── Carolina Panthers ─────────────────────────────────────────────────────
  { name: 'Bryce Young',            team: 'Carolina Panthers',      position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Diontae Johnson',        team: 'Carolina Panthers',      position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Chuba Hubbard',          team: 'Carolina Panthers',      position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Xavier Legette',         team: 'Carolina Panthers',      position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Hayden Hurst',           team: 'Carolina Panthers',      position: 'TE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Derrick Brown',          team: 'Carolina Panthers',      position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jeremy Chinn',           team: 'Carolina Panthers',      position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jadeveon Clowney',       team: 'Carolina Panthers',      position: 'DE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Donte Jackson',          team: 'Carolina Panthers',      position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Adam Thielen',           team: 'Carolina Panthers',      position: 'WR', sport: 'Football', cardType: 'Parallel' },

  // ── Chicago Bears ─────────────────────────────────────────────────────────
  { name: 'Caleb Williams',         team: 'Chicago Bears',          position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'DJ Moore',               team: 'Chicago Bears',          position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rome Odunze',            team: 'Chicago Bears',          position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Keenan Allen',           team: 'Chicago Bears',          position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Cole Kmet',              team: 'Chicago Bears',          position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: "D'Andre Swift",          team: 'Chicago Bears',          position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Montez Sweat',           team: 'Chicago Bears',          position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Tremaine Edmunds',       team: 'Chicago Bears',          position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jaylon Johnson',         team: 'Chicago Bears',          position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Kevin Byard',            team: 'Chicago Bears',          position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── Cincinnati Bengals ────────────────────────────────────────────────────
  { name: 'Joe Burrow',             team: 'Cincinnati Bengals',     position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: "Ja'Marr Chase",          team: 'Cincinnati Bengals',     position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Tee Higgins',            team: 'Cincinnati Bengals',     position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Trey Hendrickson',       team: 'Cincinnati Bengals',     position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Zack Moss',              team: 'Cincinnati Bengals',     position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Sam Hubbard',            team: 'Cincinnati Bengals',     position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Logan Wilson',           team: 'Cincinnati Bengals',     position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Cam Taylor-Britt',       team: 'Cincinnati Bengals',     position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Andrei Iosivas',         team: 'Cincinnati Bengals',     position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Ted Karras',             team: 'Cincinnati Bengals',     position: 'C',  sport: 'Football', cardType: 'Base' },

  // ── Cleveland Browns ──────────────────────────────────────────────────────
  { name: 'Deshaun Watson',         team: 'Cleveland Browns',       position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Myles Garrett',          team: 'Cleveland Browns',       position: 'DE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Nick Chubb',             team: 'Cleveland Browns',       position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Amari Cooper',           team: 'Cleveland Browns',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'David Njoku',            team: 'Cleveland Browns',       position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jerry Jeudy',            team: 'Cleveland Browns',       position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Denzel Ward',            team: 'Cleveland Browns',       position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Za\'Darius Smith',       team: 'Cleveland Browns',       position: 'DE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Martin Emerson Jr.',     team: 'Cleveland Browns',       position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Jerome Ford',            team: 'Cleveland Browns',       position: 'RB', sport: 'Football', cardType: 'Parallel' },

  // ── Dallas Cowboys ────────────────────────────────────────────────────────
  { name: 'Dak Prescott',           team: 'Dallas Cowboys',         position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'CeeDee Lamb',            team: 'Dallas Cowboys',         position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Micah Parsons',          team: 'Dallas Cowboys',         position: 'LB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Zack Martin',            team: 'Dallas Cowboys',         position: 'OG', sport: 'Football', cardType: 'Downtown' },
  { name: 'Trevon Diggs',           team: 'Dallas Cowboys',         position: 'CB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jake Ferguson',          team: 'Dallas Cowboys',         position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Rico Dowdle',            team: 'Dallas Cowboys',         position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'DaRon Bland',            team: 'Dallas Cowboys',         position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Demarcus Lawrence',      team: 'Dallas Cowboys',         position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Tyler Smith',            team: 'Dallas Cowboys',         position: 'OT', sport: 'Football', cardType: 'Parallel' },

  // ── Denver Broncos ────────────────────────────────────────────────────────
  { name: 'Bo Nix',                 team: 'Denver Broncos',         position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Pat Surtain II',         team: 'Denver Broncos',         position: 'CB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Courtland Sutton',       team: 'Denver Broncos',         position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Javonte Williams',       team: 'Denver Broncos',         position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Nik Bonitto',            team: 'Denver Broncos',         position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Troy Franklin',          team: 'Denver Broncos',         position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Jonathon Cooper',        team: 'Denver Broncos',         position: 'DE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Baron Browning',         team: 'Denver Broncos',         position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Justin Simmons',         team: 'Denver Broncos',         position: 'S',  sport: 'Football', cardType: 'Parallel' },
  { name: 'Adam Trautman',          team: 'Denver Broncos',         position: 'TE', sport: 'Football', cardType: 'Base' },

  // ── Detroit Lions ─────────────────────────────────────────────────────────
  { name: 'Jared Goff',             team: 'Detroit Lions',          position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Amon-Ra St. Brown',      team: 'Detroit Lions',          position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Aidan Hutchinson',       team: 'Detroit Lions',          position: 'DE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Jameson Williams',       team: 'Detroit Lions',          position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'David Montgomery',       team: 'Detroit Lions',          position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Penei Sewell',           team: 'Detroit Lions',          position: 'OT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Sam LaPorta',            team: 'Detroit Lions',          position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Alim McNeill',           team: 'Detroit Lions',          position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Brian Branch',           team: 'Detroit Lions',          position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Carlton Davis',          team: 'Detroit Lions',          position: 'CB', sport: 'Football', cardType: 'Net to Net' },

  // ── Green Bay Packers ─────────────────────────────────────────────────────
  { name: 'Jordan Love',            team: 'Green Bay Packers',      position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jayden Reed',            team: 'Green Bay Packers',      position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Josh Jacobs',            team: 'Green Bay Packers',      position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rashan Gary',            team: 'Green Bay Packers',      position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jaire Alexander',        team: 'Green Bay Packers',      position: 'CB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Christian Watson',       team: 'Green Bay Packers',      position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Tucker Kraft',           team: 'Green Bay Packers',      position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Kenny Clark',            team: 'Green Bay Packers',      position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'De\'Vondre Campbell',    team: 'Green Bay Packers',      position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Eric Stokes',            team: 'Green Bay Packers',      position: 'CB', sport: 'Football', cardType: 'Parallel' },

  // ── Houston Texans ────────────────────────────────────────────────────────
  { name: 'C.J. Stroud',            team: 'Houston Texans',         position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Stefon Diggs',           team: 'Houston Texans',         position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Nico Collins',           team: 'Houston Texans',         position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Joe Mixon',              team: 'Houston Texans',         position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Will Anderson Jr.',      team: 'Houston Texans',         position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Danielle Hunter',        team: 'Houston Texans',         position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Tank Dell',              team: 'Houston Texans',         position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Dalton Schultz',         team: 'Houston Texans',         position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Derek Stingley Jr.',     team: 'Houston Texans',         position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jimmie Ward',            team: 'Houston Texans',         position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── Indianapolis Colts ────────────────────────────────────────────────────
  { name: 'Anthony Richardson',     team: 'Indianapolis Colts',     position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jonathan Taylor',        team: 'Indianapolis Colts',     position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Michael Pittman Jr.',    team: 'Indianapolis Colts',     position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'DeForest Buckner',       team: 'Indianapolis Colts',     position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Josh Downs',             team: 'Indianapolis Colts',     position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Kwity Paye',             team: 'Indianapolis Colts',     position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Zaire Franklin',         team: 'Indianapolis Colts',     position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Grover Stewart',         team: 'Indianapolis Colts',     position: 'DT', sport: 'Football', cardType: 'Parallel' },
  { name: 'Julian Blackmon',        team: 'Indianapolis Colts',     position: 'S',  sport: 'Football', cardType: 'Parallel' },
  { name: 'Mo Alie-Cox',            team: 'Indianapolis Colts',     position: 'TE', sport: 'Football', cardType: 'Base' },

  // ── Jacksonville Jaguars ──────────────────────────────────────────────────
  { name: 'Trevor Lawrence',        team: 'Jacksonville Jaguars',   position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Travis Etienne Jr.',     team: 'Jacksonville Jaguars',   position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Brian Thomas Jr.',       team: 'Jacksonville Jaguars',   position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Christian Kirk',         team: 'Jacksonville Jaguars',   position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Evan Engram',            team: 'Jacksonville Jaguars',   position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Josh Hines-Allen',       team: 'Jacksonville Jaguars',   position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Travon Walker',          team: 'Jacksonville Jaguars',   position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Tyson Campbell',         team: 'Jacksonville Jaguars',   position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Foye Oluokun',           team: 'Jacksonville Jaguars',   position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Andre Cisco',            team: 'Jacksonville Jaguars',   position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── Kansas City Chiefs ────────────────────────────────────────────────────
  { name: 'Patrick Mahomes',        team: 'Kansas City Chiefs',     position: 'QB', sport: 'Football', cardType: 'Patch Jersey' },
  { name: 'Travis Kelce',           team: 'Kansas City Chiefs',     position: 'TE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Chris Jones',            team: 'Kansas City Chiefs',     position: 'DT', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Isiah Pacheco',          team: 'Kansas City Chiefs',     position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rashee Rice',            team: 'Kansas City Chiefs',     position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Xavier Worthy',          team: 'Kansas City Chiefs',     position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Hollywood Brown',        team: 'Kansas City Chiefs',     position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Trent McDuffie',         team: 'Kansas City Chiefs',     position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'George Karlaftis',       team: 'Kansas City Chiefs',     position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Nick Bolton',            team: 'Kansas City Chiefs',     position: 'LB', sport: 'Football', cardType: 'Parallel' },

  // ── Las Vegas Raiders ─────────────────────────────────────────────────────
  { name: 'Maxx Crosby',            team: 'Las Vegas Raiders',      position: 'DE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Brock Bowers',           team: 'Las Vegas Raiders',      position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jakobi Meyers',          team: 'Las Vegas Raiders',      position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Christian Wilkins',      team: 'Las Vegas Raiders',      position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Gardner Minshew',        team: 'Las Vegas Raiders',      position: 'QB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Alexander Mattison',     team: 'Las Vegas Raiders',      position: 'RB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Robert Spillane',        team: 'Las Vegas Raiders',      position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Tre\'von Moehrig',       team: 'Las Vegas Raiders',      position: 'S',  sport: 'Football', cardType: 'Parallel' },
  { name: 'Michael Mayer',          team: 'Las Vegas Raiders',      position: 'TE', sport: 'Football', cardType: 'Base' },
  { name: 'Jack Jones',             team: 'Las Vegas Raiders',      position: 'CB', sport: 'Football', cardType: 'Base' },

  // ── Los Angeles Chargers ──────────────────────────────────────────────────
  { name: 'Justin Herbert',         team: 'Los Angeles Chargers',   position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Khalil Mack',            team: 'Los Angeles Chargers',   position: 'DE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Derwin James',           team: 'Los Angeles Chargers',   position: 'S',  sport: 'Football', cardType: 'Downtown' },
  { name: 'Ladd McConkey',          team: 'Los Angeles Chargers',   position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Quentin Johnston',       team: 'Los Angeles Chargers',   position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'J.K. Dobbins',           team: 'Los Angeles Chargers',   position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Joey Bosa',              team: 'Los Angeles Chargers',   position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Asante Samuel Jr.',      team: 'Los Angeles Chargers',   position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Zion Johnson',           team: 'Los Angeles Chargers',   position: 'OG', sport: 'Football', cardType: 'Parallel' },
  { name: 'Will Dissly',            team: 'Los Angeles Chargers',   position: 'TE', sport: 'Football', cardType: 'Base' },

  // ── Los Angeles Rams ──────────────────────────────────────────────────────
  { name: 'Matthew Stafford',       team: 'Los Angeles Rams',       position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Cooper Kupp',            team: 'Los Angeles Rams',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Puka Nacua',             team: 'Los Angeles Rams',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Kyren Williams',         team: 'Los Angeles Rams',       position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Tyler Higbee',           team: 'Los Angeles Rams',       position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Kobie Turner',           team: 'Los Angeles Rams',       position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Byron Young',            team: 'Los Angeles Rams',       position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Ernest Jones',           team: 'Los Angeles Rams',       position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Ahkello Witherspoon',    team: 'Los Angeles Rams',       position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Steve Avila',            team: 'Los Angeles Rams',       position: 'C',  sport: 'Football', cardType: 'Base' },

  // ── Miami Dolphins ────────────────────────────────────────────────────────
  { name: 'Tua Tagovailoa',         team: 'Miami Dolphins',         position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Tyreek Hill',            team: 'Miami Dolphins',         position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Jaylen Waddle',          team: 'Miami Dolphins',         position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: "De'Von Achane",          team: 'Miami Dolphins',         position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jalen Ramsey',           team: 'Miami Dolphins',         position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Terron Armstead',        team: 'Miami Dolphins',         position: 'OT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jevon Holland',          team: 'Miami Dolphins',         position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Bradley Chubb',          team: 'Miami Dolphins',         position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Raheem Mostert',         team: 'Miami Dolphins',         position: 'RB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Durham Smythe',          team: 'Miami Dolphins',         position: 'TE', sport: 'Football', cardType: 'Base' },

  // ── Minnesota Vikings ─────────────────────────────────────────────────────
  { name: 'Justin Jefferson',       team: 'Minnesota Vikings',      position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Sam Darnold',            team: 'Minnesota Vikings',      position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jordan Addison',         team: 'Minnesota Vikings',      position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'T.J. Hockenson',         team: 'Minnesota Vikings',      position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Aaron Jones',            team: 'Minnesota Vikings',      position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Harrison Smith',         team: 'Minnesota Vikings',      position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Andrew Van Ginkel',      team: 'Minnesota Vikings',      position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Brian O\'Neill',         team: 'Minnesota Vikings',      position: 'OT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Byron Murphy II',        team: 'Minnesota Vikings',      position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Camryn Bynum',           team: 'Minnesota Vikings',      position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── New England Patriots ──────────────────────────────────────────────────
  { name: 'Drake Maye',             team: 'New England Patriots',   position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rhamondre Stevenson',    team: 'New England Patriots',   position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Kyle Dugger',            team: 'New England Patriots',   position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Christian Barmore',      team: 'New England Patriots',   position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Hunter Henry',           team: 'New England Patriots',   position: 'TE', sport: 'Football', cardType: 'Parallel' },
  { name: "Ja'Lynn Polk",           team: 'New England Patriots',   position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Jabrill Peppers',        team: 'New England Patriots',   position: 'S',  sport: 'Football', cardType: 'Parallel' },
  { name: 'Matthew Judon',          team: 'New England Patriots',   position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'David Andrews',          team: 'New England Patriots',   position: 'C',  sport: 'Football', cardType: 'Base' },
  { name: 'Kendrick Bourne',        team: 'New England Patriots',   position: 'WR', sport: 'Football', cardType: 'Base' },

  // ── New Orleans Saints ────────────────────────────────────────────────────
  { name: 'Derek Carr',             team: 'New Orleans Saints',     position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Alvin Kamara',           team: 'New Orleans Saints',     position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Chris Olave',            team: 'New Orleans Saints',     position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rashid Shaheed',         team: 'New Orleans Saints',     position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Cameron Jordan',         team: 'New Orleans Saints',     position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Demario Davis',          team: 'New Orleans Saints',     position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Marshon Lattimore',      team: 'New Orleans Saints',     position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Michael Thomas',         team: 'New Orleans Saints',     position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Juwan Johnson',          team: 'New Orleans Saints',     position: 'TE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Tyrann Mathieu',         team: 'New Orleans Saints',     position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── New York Giants ───────────────────────────────────────────────────────
  { name: 'Malik Nabers',           team: 'New York Giants',        position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Kayvon Thibodeaux',      team: 'New York Giants',        position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Dexter Lawrence',        team: 'New York Giants',        position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Brian Burns',            team: 'New York Giants',        position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Devin Singletary',       team: 'New York Giants',        position: 'RB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Daniel Jones',           team: 'New York Giants',        position: 'QB', sport: 'Football', cardType: 'Parallel' },
  { name: "Wan'Dale Robinson",      team: 'New York Giants',        position: 'WR', sport: 'Football', cardType: 'Parallel' },
  { name: 'Bobby Okereke',          team: 'New York Giants',        position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: "Adoree' Jackson",        team: 'New York Giants',        position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Darren Waller',          team: 'New York Giants',        position: 'TE', sport: 'Football', cardType: 'Parallel' },

  // ── New York Jets ─────────────────────────────────────────────────────────
  { name: 'Aaron Rodgers',          team: 'New York Jets',          position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Garrett Wilson',         team: 'New York Jets',          position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Breece Hall',            team: 'New York Jets',          position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Sauce Gardner',          team: 'New York Jets',          position: 'CB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Davante Adams',          team: 'New York Jets',          position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Quinnen Williams',       team: 'New York Jets',          position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'CJ Mosley',              team: 'New York Jets',          position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Haason Reddick',         team: 'New York Jets',          position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Tyler Conklin',          team: 'New York Jets',          position: 'TE', sport: 'Football', cardType: 'Base' },
  { name: 'Allen Lazard',           team: 'New York Jets',          position: 'WR', sport: 'Football', cardType: 'Base' },

  // ── Philadelphia Eagles ───────────────────────────────────────────────────
  { name: 'Jalen Hurts',            team: 'Philadelphia Eagles',    position: 'QB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'AJ Brown',               team: 'Philadelphia Eagles',    position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Saquon Barkley',         team: 'Philadelphia Eagles',    position: 'RB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'DeVonta Smith',          team: 'Philadelphia Eagles',    position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Dallas Goedert',         team: 'Philadelphia Eagles',    position: 'TE', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jalen Carter',           team: 'Philadelphia Eagles',    position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Darius Slay',            team: 'Philadelphia Eagles',    position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jordan Mailata',         team: 'Philadelphia Eagles',    position: 'OT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Landon Dickerson',       team: 'Philadelphia Eagles',    position: 'OG', sport: 'Football', cardType: 'Parallel' },
  { name: 'Reed Blankenship',       team: 'Philadelphia Eagles',    position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── Pittsburgh Steelers ───────────────────────────────────────────────────
  { name: 'T.J. Watt',              team: 'Pittsburgh Steelers',    position: 'LB', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Russell Wilson',         team: 'Pittsburgh Steelers',    position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'George Pickens',         team: 'Pittsburgh Steelers',    position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Minkah Fitzpatrick',     team: 'Pittsburgh Steelers',    position: 'S',  sport: 'Football', cardType: 'Downtown' },
  { name: 'Cam Heyward',            team: 'Pittsburgh Steelers',    position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Najee Harris',           team: 'Pittsburgh Steelers',    position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Alex Highsmith',         team: 'Pittsburgh Steelers',    position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Patrick Queen',          team: 'Pittsburgh Steelers',    position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Pat Freiermuth',         team: 'Pittsburgh Steelers',    position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Joey Porter Jr.',        team: 'Pittsburgh Steelers',    position: 'CB', sport: 'Football', cardType: 'Net to Net' },

  // ── San Francisco 49ers ───────────────────────────────────────────────────
  { name: 'Christian McCaffrey',    team: 'San Francisco 49ers',    position: 'RB', sport: 'Football', cardType: 'Patch Jersey' },
  { name: 'Nick Bosa',              team: 'San Francisco 49ers',    position: 'DE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'George Kittle',          team: 'San Francisco 49ers',    position: 'TE', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Brock Purdy',            team: 'San Francisco 49ers',    position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Deebo Samuel',           team: 'San Francisco 49ers',    position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Brandon Aiyuk',          team: 'San Francisco 49ers',    position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Trent Williams',         team: 'San Francisco 49ers',    position: 'OT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Fred Warner',            team: 'San Francisco 49ers',    position: 'LB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Talanoa Hufanga',        team: 'San Francisco 49ers',    position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Charvarius Ward',        team: 'San Francisco 49ers',    position: 'CB', sport: 'Football', cardType: 'Net to Net' },

  // ── Seattle Seahawks ──────────────────────────────────────────────────────
  { name: 'DK Metcalf',             team: 'Seattle Seahawks',       position: 'WR', sport: 'Football', cardType: 'Kaboom' },
  { name: 'Geno Smith',             team: 'Seattle Seahawks',       position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Tyler Lockett',          team: 'Seattle Seahawks',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Kenneth Walker III',     team: 'Seattle Seahawks',       position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Devon Witherspoon',      team: 'Seattle Seahawks',       position: 'CB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Bobby Wagner',           team: 'Seattle Seahawks',       position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Boye Mafe',              team: 'Seattle Seahawks',       position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Noah Fant',              team: 'Seattle Seahawks',       position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Quandre Diggs',          team: 'Seattle Seahawks',       position: 'S',  sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jordyn Brooks',          team: 'Seattle Seahawks',       position: 'LB', sport: 'Football', cardType: 'Parallel' },

  // ── Tampa Bay Buccaneers ──────────────────────────────────────────────────
  { name: 'Baker Mayfield',         team: 'Tampa Bay Buccaneers',   position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Mike Evans',             team: 'Tampa Bay Buccaneers',   position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Chris Godwin',           team: 'Tampa Bay Buccaneers',   position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Antoine Winfield Jr.',   team: 'Tampa Bay Buccaneers',   position: 'S',  sport: 'Football', cardType: 'Downtown' },
  { name: 'Vita Vea',               team: 'Tampa Bay Buccaneers',   position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'Rachaad White',          team: 'Tampa Bay Buccaneers',   position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Lavonte David',          team: 'Tampa Bay Buccaneers',   position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Joe Tryon-Shoyinka',     team: 'Tampa Bay Buccaneers',   position: 'DE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Jamel Dean',             team: 'Tampa Bay Buccaneers',   position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Cade Otton',             team: 'Tampa Bay Buccaneers',   position: 'TE', sport: 'Football', cardType: 'Parallel' },

  // ── Tennessee Titans ──────────────────────────────────────────────────────
  { name: 'Will Levis',             team: 'Tennessee Titans',       position: 'QB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Tony Pollard',           team: 'Tennessee Titans',       position: 'RB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Calvin Ridley',          team: 'Tennessee Titans',       position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jeffery Simmons',        team: 'Tennessee Titans',       position: 'DT', sport: 'Football', cardType: 'Downtown' },
  { name: 'L\'Jarius Sneed',        team: 'Tennessee Titans',       position: 'CB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'DeAndre Hopkins',        team: 'Tennessee Titans',       position: 'WR', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Chigoziem Okonkwo',      team: 'Tennessee Titans',       position: 'TE', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Harold Landry III',      team: 'Tennessee Titans',       position: 'LB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Roger McCreary',         team: 'Tennessee Titans',       position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Kevin Byard',            team: 'Tennessee Titans',       position: 'S',  sport: 'Football', cardType: 'Parallel' },

  // ── Washington Commanders ─────────────────────────────────────────────────
  { name: 'Jayden Daniels',         team: 'Washington Commanders',  position: 'QB', sport: 'Football', cardType: 'Downtown' },
  { name: 'Terry McLaurin',         team: 'Washington Commanders',  position: 'WR', sport: 'Football', cardType: 'Downtown' },
  { name: 'Jonathan Allen',         team: 'Washington Commanders',  position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Daron Payne',            team: 'Washington Commanders',  position: 'DT', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Brian Robinson Jr.',     team: 'Washington Commanders',  position: 'RB', sport: 'Football', cardType: 'Net to Net' },
  { name: 'Frankie Luvu',           team: 'Washington Commanders',  position: 'LB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Kendall Fuller',         team: 'Washington Commanders',  position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Emmanuel Forbes',        team: 'Washington Commanders',  position: 'CB', sport: 'Football', cardType: 'Parallel' },
  { name: 'Zach Ertz',              team: 'Washington Commanders',  position: 'TE', sport: 'Football', cardType: 'Parallel' },
  { name: 'Ben Sinnott',            team: 'Washington Commanders',  position: 'TE', sport: 'Football', cardType: 'Base' },
]

export default nflPlayers
